# Generated by Django 5.2 on 2025-05-02 21:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Username at the time of the action (in case user is deleted)",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("view", "View"),
                            ("escalate", "Escalate"),
                            ("assign", "Assign"),
                            ("complete", "Complete"),
                            ("close", "Close"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("ingest", "Ingest"),
                            ("export", "Export"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Action",
                    ),
                ),
                (
                    "action_details",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Action Details",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("alert", "Alert"),
                            ("incident", "Incident"),
                            ("task", "Task"),
                            ("observable", "Observable"),
                            ("company", "Company"),
                            ("user", "User"),
                            ("system", "System"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Entity Type",
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Entity ID"
                    ),
                ),
                (
                    "entity_name",
                    models.CharField(
                        blank=True,
                        help_text="Name or title of the entity at the time of the action",
                        max_length=255,
                        null=True,
                        verbose_name="Entity Name",
                    ),
                ),
                (
                    "company_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Company ID"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Company Name",
                    ),
                ),
                (
                    "request_method",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Request Method",
                    ),
                ),
                (
                    "request_path",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Request Path",
                    ),
                ),
                (
                    "request_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Request Data"
                    ),
                ),
                (
                    "response_status",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Response Status"
                    ),
                ),
                (
                    "additional_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional Data"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the action occurred",
                        verbose_name="Timestamp",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="audit_logs__user_id_a5e0ec_idx"
                    ),
                    models.Index(
                        fields=["entity_type"], name="audit_logs__entity__5f3d85_idx"
                    ),
                    models.Index(
                        fields=["action"], name="audit_logs__action_235999_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="audit_logs__timesta_aec53a_idx"
                    ),
                    models.Index(
                        fields=["company_id"], name="audit_logs__company_8a18a2_idx"
                    ),
                ],
            },
        ),
    ]
