# Generated by Django 5.2 on 2025-05-05 17:18

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alerts", "0003_initial"),
        ("companies", "0001_initial"),
        ("incidents", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MISPServer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("url", models.URLField(max_length=255, verbose_name="URL")),
                ("api_key", models.CharField(max_length=255, verbose_name="API Key")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "verify_ssl",
                    models.BooleanField(default=True, verbose_name="Verify SSL"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Sync"
                    ),
                ),
                (
                    "sync_interval_hours",
                    models.PositiveIntegerField(
                        default=24, verbose_name="Sync Interval (hours)"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="misp_servers",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_misp_servers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "MISP Server",
                "verbose_name_plural": "MISP Servers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MISPEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="UUID"
                    ),
                ),
                ("misp_id", models.PositiveIntegerField(verbose_name="MISP ID")),
                ("misp_uuid", models.UUIDField(unique=True, verbose_name="MISP UUID")),
                ("info", models.CharField(max_length=255, verbose_name="Info/Title")),
                ("date", models.DateField(verbose_name="Event Date")),
                (
                    "threat_level_id",
                    models.PositiveSmallIntegerField(
                        default=2, verbose_name="Threat Level ID"
                    ),
                ),
                (
                    "analysis",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Analysis"
                    ),
                ),
                (
                    "distribution",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Distribution"
                    ),
                ),
                (
                    "published",
                    models.BooleanField(default=False, verbose_name="Published"),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Tags",
                    ),
                ),
                (
                    "org_name",
                    models.CharField(max_length=255, verbose_name="Organization Name"),
                ),
                (
                    "orgc_name",
                    models.CharField(
                        max_length=255, verbose_name="Creator Organization Name"
                    ),
                ),
                ("timestamp", models.DateTimeField(verbose_name="Timestamp")),
                ("raw_data", models.JSONField(default=dict, verbose_name="Raw Data")),
                (
                    "alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="misp_events",
                        to="alerts.alert",
                        verbose_name="Related Alert",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="misp_events",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="misp_events",
                        to="incidents.incident",
                        verbose_name="Related Incident",
                    ),
                ),
                (
                    "misp_server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="api.mispserver",
                        verbose_name="MISP Server",
                    ),
                ),
            ],
            options={
                "verbose_name": "MISP Event",
                "verbose_name_plural": "MISP Events",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="MISPAttribute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="UUID"
                    ),
                ),
                ("misp_id", models.PositiveIntegerField(verbose_name="MISP ID")),
                ("misp_uuid", models.UUIDField(unique=True, verbose_name="MISP UUID")),
                ("type", models.CharField(max_length=100, verbose_name="Type")),
                ("category", models.CharField(max_length=100, verbose_name="Category")),
                ("value", models.TextField(verbose_name="Value")),
                ("to_ids", models.BooleanField(default=False, verbose_name="To IDS")),
                (
                    "distribution",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Distribution"
                    ),
                ),
                ("timestamp", models.DateTimeField(verbose_name="Timestamp")),
                ("comment", models.TextField(blank=True, verbose_name="Comment")),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Tags",
                    ),
                ),
                ("raw_data", models.JSONField(default=dict, verbose_name="Raw Data")),
                (
                    "company",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="misp_attributes",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="api.mispevent",
                        verbose_name="MISP Event",
                    ),
                ),
            ],
            options={
                "verbose_name": "MISP Attribute",
                "verbose_name_plural": "MISP Attributes",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["event"], name="api_mispatt_event_i_191391_idx"
                    ),
                    models.Index(fields=["type"], name="api_mispatt_type_8831f9_idx"),
                    models.Index(
                        fields=["category"], name="api_mispatt_categor_aaca48_idx"
                    ),
                    models.Index(
                        fields=["to_ids"], name="api_mispatt_to_ids_ac2dce_idx"
                    ),
                    models.Index(
                        fields=["misp_id"], name="api_mispatt_misp_id_d62ef4_idx"
                    ),
                    models.Index(
                        fields=["misp_uuid"], name="api_mispatt_misp_uu_ec6ee5_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MISPObject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="UUID"
                    ),
                ),
                ("misp_id", models.PositiveIntegerField(verbose_name="MISP ID")),
                ("misp_uuid", models.UUIDField(unique=True, verbose_name="MISP UUID")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "meta_category",
                    models.CharField(max_length=255, verbose_name="Meta Category"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "template_uuid",
                    models.CharField(max_length=36, verbose_name="Template UUID"),
                ),
                (
                    "template_version",
                    models.CharField(max_length=10, verbose_name="Template Version"),
                ),
                (
                    "distribution",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Distribution"
                    ),
                ),
                ("timestamp", models.DateTimeField(verbose_name="Timestamp")),
                ("comment", models.TextField(blank=True, verbose_name="Comment")),
                ("deleted", models.BooleanField(default=False, verbose_name="Deleted")),
                ("raw_data", models.JSONField(default=dict, verbose_name="Raw Data")),
                (
                    "company",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="misp_objects",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objects",
                        to="api.mispevent",
                        verbose_name="MISP Event",
                    ),
                ),
            ],
            options={
                "verbose_name": "MISP Object",
                "verbose_name_plural": "MISP Objects",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["event"], name="api_mispobj_event_i_181423_idx"
                    ),
                    models.Index(fields=["name"], name="api_mispobj_name_56ac7e_idx"),
                    models.Index(
                        fields=["meta_category"], name="api_mispobj_meta_ca_b0f78f_idx"
                    ),
                    models.Index(
                        fields=["deleted"], name="api_mispobj_deleted_624c0c_idx"
                    ),
                    models.Index(
                        fields=["misp_id"], name="api_mispobj_misp_id_ec8385_idx"
                    ),
                    models.Index(
                        fields=["misp_uuid"], name="api_mispobj_misp_uu_0a69b1_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="mispserver",
            index=models.Index(
                fields=["company"], name="api_mispser_company_de9e2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mispserver",
            index=models.Index(
                fields=["is_active"], name="api_mispser_is_acti_596eac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mispserver",
            index=models.Index(
                fields=["last_sync"], name="api_mispser_last_sy_e5e576_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mispserver",
            constraint=models.UniqueConstraint(
                fields=("name", "company"), name="unique_misp_server_name_per_company"
            ),
        ),
        migrations.AddIndex(
            model_name="mispevent",
            index=models.Index(
                fields=["company"], name="api_mispeve_company_fdff5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mispevent",
            index=models.Index(
                fields=["misp_server"], name="api_mispeve_misp_se_5cba55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mispevent",
            index=models.Index(
                fields=["timestamp"], name="api_mispeve_timesta_b0f3c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mispevent",
            index=models.Index(
                fields=["misp_id"], name="api_mispeve_misp_id_53d867_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mispevent",
            index=models.Index(
                fields=["misp_uuid"], name="api_mispeve_misp_uu_aab0ba_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mispevent",
            constraint=models.UniqueConstraint(
                fields=("misp_id", "misp_server"), name="unique_event_per_misp_server"
            ),
        ),
    ]
