# Generated by Django 5.2 on 2025-05-02 21:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("sentinelvision", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="analyzermodule",
            name="cron_schedule",
            field=models.CharField(
                blank=True,
                help_text='Cron expression for scheduled execution (e.g., "0 */12 * * *" for every 12 hours)',
                max_length=100,
                verbose_name="Cron Schedule",
            ),
        ),
        migrations.AddField(
            model_name="feedmodule",
            name="cron_schedule",
            field=models.CharField(
                blank=True,
                help_text='Cron expression for scheduled execution (e.g., "0 */12 * * *" for every 12 hours)',
                max_length=100,
                verbose_name="Cron Schedule",
            ),
        ),
        migrations.AddField(
            model_name="respondermodule",
            name="cron_schedule",
            field=models.CharField(
                blank=True,
                help_text='Cron expression for scheduled execution (e.g., "0 */12 * * *" for every 12 hours)',
                max_length=100,
                verbose_name="Cron Schedule",
            ),
        ),
        migrations.AlterField(
            model_name="analyzermodule",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave empty for global modules accessible only to superadmins",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_modules",
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="feedmodule",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave empty for global modules accessible only to superadmins",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_modules",
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="respondermodule",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave empty for global modules accessible only to superadmins",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_modules",
                to="companies.company",
            ),
        ),
        migrations.CreateModel(
            name="FeedExecutionRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Execution"),
                            ("scheduled", "Scheduled Execution"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="Execution Source",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Execution Status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Started At"
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ended At"
                    ),
                ),
                (
                    "log",
                    models.TextField(
                        blank=True,
                        help_text="Detailed log of the execution process",
                        verbose_name="Execution Log",
                    ),
                ),
                (
                    "iocs_processed",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of IOCs processed during execution",
                        verbose_name="IOCs Processed",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if execution failed",
                        verbose_name="Error Message",
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered the execution (null if automated)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feed_executions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Executed By",
                    ),
                ),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_records",
                        to="sentinelvision.feedmodule",
                        verbose_name="Feed Module",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feed Execution Record",
                "verbose_name_plural": "Feed Execution Records",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["feed", "-started_at"],
                        name="sentinelvis_feed_id_d328c3_idx",
                    ),
                    models.Index(
                        fields=["status"], name="sentinelvis_status_30fc2c_idx"
                    ),
                    models.Index(
                        fields=["source"], name="sentinelvis_source_602205_idx"
                    ),
                ],
            },
        ),
    ]
