# Generated by Django 5.2 on 2025-05-03 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sentinelvision", "0001_initial"),
    ]

    operations = []
