# Generated by Django 5.2 on 2025-05-03 15:13

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Severity",
                    ),
                ),
                ("source", models.CharField(max_length=100, verbose_name="Source")),
                (
                    "source_ref",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Source Reference"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("escalated", "Escalated"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Tags",
                    ),
                ),
                (
                    "tlp",
                    models.IntegerField(
                        choices=[(0, "White"), (1, "Green"), (2, "Amber"), (3, "Red")],
                        default=2,
                        verbose_name="TLP (Traffic Light Protocol)",
                    ),
                ),
                (
                    "pap",
                    models.IntegerField(
                        choices=[(0, "White"), (1, "Green"), (2, "Amber")],
                        default=2,
                        verbose_name="PAP (Permissible Actions Protocol)",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Alert Date"
                    ),
                ),
                (
                    "external_source",
                    models.CharField(
                        blank=True,
                        help_text="External system that generated the alert (e.g., MISP, SIEM, Firewall)",
                        max_length=100,
                        verbose_name="External Source",
                    ),
                ),
                (
                    "observable_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="List of observables (IPs, domains, hashes) related to this alert",
                        verbose_name="Observable Data",
                    ),
                ),
                (
                    "artifact_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of attached observables/artifacts",
                        verbose_name="Artifact Count",
                    ),
                ),
                (
                    "ioc_tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        help_text="Specific tags for Indicators of Compromise (IOCs)",
                        size=None,
                        verbose_name="IOC Tags",
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Original alert data as received from the source system",
                        verbose_name="Raw Payload",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alert",
                "verbose_name_plural": "Alerts",
                "ordering": ["-created_at"],
            },
        ),
    ]
