# Generated by Django 5.2 on 2025-05-03 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alerts", "0002_initial"),
        ("mitre", "0001_initial"),
        ("observables", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="observables",
            field=models.ManyToManyField(
                blank=True,
                related_name="alerts",
                to="observables.observable",
                verbose_name="Observables",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="primary_technique",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary MITRE ATT&CK technique associated with this alert",
                limit_choices_to={"is_subtechnique": False},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_technique_alerts",
                to="mitre.mitretechnique",
                verbose_name="Primary MITRE Technique",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="sub_technique",
            field=models.ForeignKey(
                blank=True,
                help_text="MITRE ATT&CK sub-technique associated with this alert",
                limit_choices_to={"is_subtechnique": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_technique_alerts",
                to="mitre.mitretechnique",
                verbose_name="MITRE Sub-technique",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["company", "status"], name="alerts_aler_company_9bf118_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["company", "severity"], name="alerts_aler_company_afdc3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["created_at"], name="alerts_aler_created_8af5ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(fields=["date"], name="alerts_aler_date_566c67_idx"),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["source_ref"], name="alerts_aler_source__412c77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["external_source"], name="alerts_aler_externa_90ca89_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="alert",
            constraint=models.UniqueConstraint(
                fields=("source_ref", "external_source", "company"),
                name="unique_alert_per_source_ref_and_company",
            ),
        ),
    ]
