# Generated by Django 5.2 on 2025-05-03 15:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="name"),
                ),
            ],
            options={
                "verbose_name": "company",
                "verbose_name_plural": "companies",
                "ordering": ["name"],
            },
        ),
    ]
