# Generated by Django 5.2 on 2025-05-03 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alerts", "0003_initial"),
        ("companies", "0001_initial"),
        ("incidents", "0001_initial"),
        ("mitre", "0001_initial"),
        ("observables", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="primary_technique",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary MITRE ATT&CK technique associated with this incident",
                limit_choices_to={"is_subtechnique": False},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_technique_incidents",
                to="mitre.mitretechnique",
                verbose_name="Primary MITRE Technique",
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="related_alerts",
            field=models.ManyToManyField(
                blank=True,
                related_name="incidents",
                to="alerts.alert",
                verbose_name="Related Alerts",
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="sub_technique",
            field=models.ForeignKey(
                blank=True,
                help_text="MITRE ATT&CK sub-technique associated with this incident",
                limit_choices_to={"is_subtechnique": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_technique_incidents",
                to="mitre.mitretechnique",
                verbose_name="MITRE Sub-technique",
            ),
        ),
        migrations.AddField(
            model_name="incidentobservable",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incident_observable_links",
                to="companies.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="incidentobservable",
            name="incident",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incident_observables",
                to="incidents.incident",
                verbose_name="Incident",
            ),
        ),
        migrations.AddField(
            model_name="incidentobservable",
            name="observable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incident_observables",
                to="observables.observable",
                verbose_name="Observable",
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="observables",
            field=models.ManyToManyField(
                blank=True,
                related_name="incidents",
                through="incidents.IncidentObservable",
                to="observables.observable",
                verbose_name="Observables",
            ),
        ),
        migrations.AddField(
            model_name="incidenttask",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assignee",
            ),
        ),
        migrations.AddField(
            model_name="incidenttask",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incident_tasks",
                to="companies.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="incidenttask",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="incidenttask",
            name="incident",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="incidents.incident",
                verbose_name="Incident",
            ),
        ),
        migrations.AddField(
            model_name="timelineevent",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeline_events",
                to="companies.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="timelineevent",
            name="incident",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeline_events",
                to="incidents.incident",
                verbose_name="Incident",
            ),
        ),
        migrations.AddField(
            model_name="timelineevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timeline_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddIndex(
            model_name="incidentobservable",
            index=models.Index(
                fields=["incident"], name="incidents_i_inciden_099f09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incidentobservable",
            index=models.Index(
                fields=["observable"], name="incidents_i_observa_486862_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incidentobservable",
            index=models.Index(
                fields=["company"], name="incidents_i_company_1f07aa_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="incidentobservable",
            unique_together={("incident", "observable")},
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["company", "status"], name="incidents_i_company_caa603_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["company", "severity"], name="incidents_i_company_048421_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["created_at"], name="incidents_i_created_8be57d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["start_date"], name="incidents_i_start_d_203147_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["end_date"], name="incidents_i_end_dat_0f2ca7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["assignee"], name="incidents_i_assigne_a51783_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["impact_score"], name="incidents_i_impact__b75d00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incidenttask",
            index=models.Index(
                fields=["incident"], name="incidents_i_inciden_276527_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incidenttask",
            index=models.Index(
                fields=["assignee"], name="incidents_i_assigne_550465_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incidenttask",
            index=models.Index(
                fields=["company"], name="incidents_i_company_8e53f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timelineevent",
            index=models.Index(
                fields=["incident"], name="incidents_t_inciden_e3f2ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timelineevent",
            index=models.Index(
                fields=["company"], name="incidents_t_company_e2b3d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timelineevent",
            index=models.Index(
                fields=["timestamp"], name="incidents_t_timesta_91232a_idx"
            ),
        ),
    ]
